name: Build Debian Package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Debian Package
      run: sudo apt-get install debhelper dh-virtualenv

    - name: Build Debian Package
      run: dpkg-buildpackage -b
