name: Build Debian Package

on:
  push:
    branches: [ master ]

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get install git-buildpackage

      - name: Update Changelog
        run: gbp dch

      - name: Push changes
        uses: github-actions-x/commit@v2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'Changelog'
          force-add: 'true'
          files: debian/changelog
          name: Github Actions
          email: mail@mrgoro.de

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install debhelper dh-virtualenv

    - name: Build Debian Package
      run: dpkg-buildpackage

    - name: Copy Debian Packages
      run: |
        mkdir release
        cp ../sim-tool_* ./release

    - name: Upload Debian Package
      uses: actions/upload-artifact@v2-preview
      with:
        name: sim-tool-debian.zip
        path: release/sim-tool_*
