name: Build Debian Package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install debhelper dh-virtualenv

    - name: Build Debian Package
      run: dpkg-buildpackage

    - name: Copy Debian Packages
      run: |
        mk dir release
        cp ../sim-tool_* ./release

    - name: Upload Debian Package
      uses: actions/upload-artifact@v2-preview
      with:
        name: sim-tool-debian.zip
        path: release/sim-tool_*
