name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set version number
      id: get-version
      run: |
        echo ::set-output name=version::$(/bin/echo "${{ github.ref }}" | cut -d'v' -f 2)

    - name: Install Dependencies
      run: sudo apt-get install debhelper dh-virtualenv git-buildpackage

    - name: Update Changelog
      run: gbp dch

    - name: Push changes
      uses: github-actions-x/commit@v2.5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: ${{ github.ref }}
        commit-message: 'Changelog'
        force-add: 'true'
        files: debian/changelog
        name: Github Actions
        email: mail@mrgoro.de

    - name: Build Debian Package
      run: dpkg-buildpackage

    - name: Copy Debian Packages
      run: |
        mkdir release
        cp ../sim-tool_* ./release

    - name: Upload Debian Package
      uses: actions/upload-artifact@v2-preview
      with:
        name: sim-tool-${{ steps.get-version.outputs.version }}-debian.zip
        path: release/sim-tool_*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ./release/sim-tool_${{ steps.get-version.outputs.version }}_all.deb
        asset_name: sim-tool_${{ steps.get-version.outputs.version }}_all.deb
        asset_content_type: application/x-deb
