name: Update Changelog

on:
  push:
    branches: [ master ]
    paths:
      - 'version'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set version number
      id: get-version
      run: |
        echo ::set-output name=version::$(cat version)

    - name: Install Dependencies
      run: sudo apt-get install git-buildpackage

    - name: Update Changelog
      run: gbp dch --release --commit --new-version="${{ steps.get-version.outputs.version }}" --spawn-editor=never

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
